application: simplepitch
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "1h"

handlers:
- url: /favicon\.ico
  static_files: webapp/favicon.ico
  upload: webapp/favicon.ico

# Order does matter
- url: /mp3/
  static_dir: webapp/mp3
  expiration: "7d"

- url: /
  static_files: webapp/index.html
  upload: webapp/index.html

- url: /
  static_dir: webapp/


skip_files:
# Configuration files are sent to the server seperately.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^webapp/sass/.*
- ^webapp/config.rb

libraries:
- name: lxml
  version: "latest"


env_variables:
  IS_APP_ENGINE: 'true'
